# Template config, need to change dump_dir, data.root_dir and tokenizer.path
# Evals can be activated by uncommenting its config
# python -m lingua.stool config=apps/main/configs/debug.yaml nodes=8 account=fair_amaia_cw_codegen qos=lowest

# dump_dir: !!CHANGETHIS!!
name: "1b_Hawk"
steps: 60_000
probe_freq: null #1000

seed: 777
optim:
  lr: 3.0e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 10.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1
  detect_anomaly: false

model_type: "hawk"
model:
  dim: 2048
  n_layers: 25
  n_heads: 22
  conv_size: 4

data:
  root_dir: data/shuffled
  sources:
    dclm_baseline_1.0: 100.0
  batch_size: 8
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    name: sp
    path: tokenizers/tokenizer_final_32k.minus_inf_ws.model

profiling:
  run: true

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: 2

logging:
  freq: 1

async_eval_gpus: 8
eval:
  dataset_dir: datasets/eval
  harness:
    tasks:
      - hellaswag
      - nq_open
      - piqa
      - siqa
      - csatqa
      - winogrande
      - arc
      - race
      - gsm8k
      - bbh
      - mmlu
  generator:
    compile_prefilling: false
    reduce_generation_overhead: true
    max_tokens: 16384
    dtype: bf16

  mp_size: 1
