#python -m lingua.stool config=apps/main/configs/llama2_7B.yaml nodes=32 account=fair_amaia_cw_codegen qos=lowest
# dump_dir: !!CHANGETHIS!!
name: "7b_hawk"
steps: 100_000
grad_acc_steps: 1

seed: 777
optim:
  lr: 1.0e-3
  weight_decay: 0.1
  warmup: 2000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model_type: "hawk"
model:
  dim: 4096
  n_layers: 32
  n_heads: 28
  lru_dim_multiplier: 0.65
  conv_size: 4

data:
  root_dir: data/shuffled
  sources:
    dclm_baseline_1.0: 1.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  tokenizer:
    name: tiktoken
    path: tokenizers/cl_toplang_128k.tiktoken

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 10000
    keep: -1
  eval:
    every: 1000
    keep: 3

logging:
  freq: 1

async_eval_gpus: 8
eval:
  dataset_dir: datasets/eval
  harness:
    tasks:
      - hellaswag
      - nq_open
      - piqa
      - siqa
      - csatqa
      - winogrande
      - arc
      - race
      - gsm8k
      - bbh
      - mmlu
  generator:
    max_tokens: 16384
    dtype: bf16

  mp_size: 1
