# Template config, need to change dump_dir, data.root_dir and tokenizer.path
# Evals can be activated by uncommenting its config
# python -m lingua.stool config=apps/main/configs/debug.yaml nodes=8 account=fair_amaia_cw_codegen qos=lowest

# dump_dir: !!!CHANGE_THIS!!!
name: "debug"
steps: 100_000
probe_freq: 1000

seed: 777
optim:
  lr: 1.0e-3
  weight_decay: 0.1
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 4096
  n_heads: 64
  n_groups: 1
  state_dim: 128
  conv_size: 4
  n_layers: 64
  dt_bias: false
  D_has_head_dim: false
  init_args:
    # dt_max: 0.001
    # dt_min: 0.00001

    A_init_min: 0.01
    A_init_max: 2

data:
  root_dir: data/shuffled
  sources:
    dclm_baseline_1.0: 1.0
  batch_size: 2
  prefetch_size: 64
  seq_len: 4096
  n_views: 2
  load_async: true
  tokenizer:
    name: tiktoken
    path: tokenizers/cl_toplang_128k.tiktoken

profiling:
  run: true

checkpoint:
  dump:
    every: 1000
    keep: 3
  eval:
    every: 5000
    keep: 2

logging:
  freq: 1

async_eval_gpus: 32
eval:
  harness:
    tasks:
      - hellaswag
      - nq_open
      - piqa
      - siqa
      - csatqa
      - winogrande
      - arc
      - race
      - gsm8k
      - bbh
      - mmlu
  generator:
    compile_prefilling: false
    reduce_generation_overhead: false
    max_tokens: 8192
    dtype: bf16

  mp_size: 1
